/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndustriRouteImport } from './routes/industri'
import { Route as KebijakanPrivasiRouteImport } from './routes/kebijakan-privasi'
import { Route as KesehatanRouteImport } from './routes/kesehatan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LayananIndividuRouteImport } from './routes/layanan-individu'
import { Route as PelatihanRouteImport } from './routes/pelatihan'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolusiKorporatRouteImport } from './routes/solusi-korporat'
import { Route as SyaratKetentuanRouteImport } from './routes/syarat-ketentuan'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as TokohSentralRouteImport } from './routes/tokoh-sentral'
import { Route as ArtikelIndexRouteImport } from './routes/artikel.index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as IndustriIndexRouteImport } from './routes/industri.index'
import { Route as IndustriSlugRouteImport } from './routes/industri.$slug'
import { Route as LayananSlugRouteImport } from './routes/layanan.$slug'
import { Route as ProgramIndexRouteImport } from './routes/program.index'
import { Route as ProgramMppRouteImport } from './routes/program.mpp'
import { Route as TentangKamiIndexRouteImport } from './routes/tentang-kami.index'
import { Route as TentangKamiLegalitasRouteImport } from './routes/tentang-kami.legalitas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriRoute = IndustriRouteImport.update({
  id: '/industri',
  path: '/industri',
  getParentRoute: () => rootRouteImport,
} as any)
const KebijakanPrivasiRoute = KebijakanPrivasiRouteImport.update({
  id: '/kebijakan-privasi',
  path: '/kebijakan-privasi',
  getParentRoute: () => rootRouteImport,
} as any)
const KesehatanRoute = KesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananIndividuRoute = LayananIndividuRouteImport.update({
  id: '/layanan-individu',
  path: '/layanan-individu',
  getParentRoute: () => rootRouteImport,
} as any)
const PelatihanRoute = PelatihanRouteImport.update({
  id: '/pelatihan',
  path: '/pelatihan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolusiKorporatRoute = SolusiKorporatRouteImport.update({
  id: '/solusi-korporat',
  path: '/solusi-korporat',
  getParentRoute: () => rootRouteImport,
} as any)
const SyaratKetentuanRoute = SyaratKetentuanRouteImport.update({
  id: '/syarat-ketentuan',
  path: '/syarat-ketentuan',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const TokohSentralRoute = TokohSentralRouteImport.update({
  id: '/tokoh-sentral',
  path: '/tokoh-sentral',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtikelRoute,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtikelRoute,
} as any)
const IndustriIndexRoute = IndustriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriRoute,
} as any)
const IndustriSlugRoute = IndustriSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriRoute,
} as any)
const LayananSlugRoute = LayananSlugRouteImport.update({
  id: '/layanan/$slug',
  path: '/layanan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramRoute,
} as any)
const ProgramMppRoute = ProgramMppRouteImport.update({
  id: '/mpp',
  path: '/mpp',
  getParentRoute: () => ProgramRoute,
} as any)
const TentangKamiIndexRoute = TentangKamiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TentangKamiRoute,
} as any)
const TentangKamiLegalitasRoute = TentangKamiLegalitasRouteImport.update({
  id: '/legalitas',
  path: '/legalitas',
  getParentRoute: () => TentangKamiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/faq': typeof FaqRoute
  '/industri': typeof IndustriRouteWithChildren
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kesehatan': typeof KesehatanRoute
  '/kontak': typeof KontakRoute
  '/layanan-individu': typeof LayananIndividuRoute
  '/pelatihan': typeof PelatihanRoute
  '/professionals': typeof ProfessionalsRoute
  '/program': typeof ProgramRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solusi-korporat': typeof SolusiKorporatRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRouteWithChildren
  '/testimoni': typeof TestimoniRoute
  '/tokoh-sentral': typeof TokohSentralRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/industri/$slug': typeof IndustriSlugRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/program/mpp': typeof ProgramMppRoute
  '/tentang-kami/legalitas': typeof TentangKamiLegalitasRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/industri/': typeof IndustriIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kesehatan': typeof KesehatanRoute
  '/kontak': typeof KontakRoute
  '/layanan-individu': typeof LayananIndividuRoute
  '/pelatihan': typeof PelatihanRoute
  '/professionals': typeof ProfessionalsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solusi-korporat': typeof SolusiKorporatRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/testimoni': typeof TestimoniRoute
  '/tokoh-sentral': typeof TokohSentralRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/industri/$slug': typeof IndustriSlugRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/program/mpp': typeof ProgramMppRoute
  '/tentang-kami/legalitas': typeof TentangKamiLegalitasRoute
  '/artikel': typeof ArtikelIndexRoute
  '/industri': typeof IndustriIndexRoute
  '/program': typeof ProgramIndexRoute
  '/tentang-kami': typeof TentangKamiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/faq': typeof FaqRoute
  '/industri': typeof IndustriRouteWithChildren
  '/kebijakan-privasi': typeof KebijakanPrivasiRoute
  '/kesehatan': typeof KesehatanRoute
  '/kontak': typeof KontakRoute
  '/layanan-individu': typeof LayananIndividuRoute
  '/pelatihan': typeof PelatihanRoute
  '/professionals': typeof ProfessionalsRoute
  '/program': typeof ProgramRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solusi-korporat': typeof SolusiKorporatRoute
  '/syarat-ketentuan': typeof SyaratKetentuanRoute
  '/tentang-kami': typeof TentangKamiRouteWithChildren
  '/testimoni': typeof TestimoniRoute
  '/tokoh-sentral': typeof TokohSentralRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/industri/$slug': typeof IndustriSlugRoute
  '/layanan/$slug': typeof LayananSlugRoute
  '/program/mpp': typeof ProgramMppRoute
  '/tentang-kami/legalitas': typeof TentangKamiLegalitasRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/industri/': typeof IndustriIndexRoute
  '/program/': typeof ProgramIndexRoute
  '/tentang-kami/': typeof TentangKamiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/faq'
    | '/industri'
    | '/kebijakan-privasi'
    | '/kesehatan'
    | '/kontak'
    | '/layanan-individu'
    | '/pelatihan'
    | '/professionals'
    | '/program'
    | '/sitemap.xml'
    | '/solusi-korporat'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/testimoni'
    | '/tokoh-sentral'
    | '/artikel/$slug'
    | '/industri/$slug'
    | '/layanan/$slug'
    | '/program/mpp'
    | '/tentang-kami/legalitas'
    | '/artikel/'
    | '/industri/'
    | '/program/'
    | '/tentang-kami/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/kebijakan-privasi'
    | '/kesehatan'
    | '/kontak'
    | '/layanan-individu'
    | '/pelatihan'
    | '/professionals'
    | '/sitemap.xml'
    | '/solusi-korporat'
    | '/syarat-ketentuan'
    | '/testimoni'
    | '/tokoh-sentral'
    | '/artikel/$slug'
    | '/industri/$slug'
    | '/layanan/$slug'
    | '/program/mpp'
    | '/tentang-kami/legalitas'
    | '/artikel'
    | '/industri'
    | '/program'
    | '/tentang-kami'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/faq'
    | '/industri'
    | '/kebijakan-privasi'
    | '/kesehatan'
    | '/kontak'
    | '/layanan-individu'
    | '/pelatihan'
    | '/professionals'
    | '/program'
    | '/sitemap.xml'
    | '/solusi-korporat'
    | '/syarat-ketentuan'
    | '/tentang-kami'
    | '/testimoni'
    | '/tokoh-sentral'
    | '/artikel/$slug'
    | '/industri/$slug'
    | '/layanan/$slug'
    | '/program/mpp'
    | '/tentang-kami/legalitas'
    | '/artikel/'
    | '/industri/'
    | '/program/'
    | '/tentang-kami/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRouteWithChildren
  FaqRoute: typeof FaqRoute
  IndustriRoute: typeof IndustriRouteWithChildren
  KebijakanPrivasiRoute: typeof KebijakanPrivasiRoute
  KesehatanRoute: typeof KesehatanRoute
  KontakRoute: typeof KontakRoute
  LayananIndividuRoute: typeof LayananIndividuRoute
  PelatihanRoute: typeof PelatihanRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ProgramRoute: typeof ProgramRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolusiKorporatRoute: typeof SolusiKorporatRoute
  SyaratKetentuanRoute: typeof SyaratKetentuanRoute
  TentangKamiRoute: typeof TentangKamiRouteWithChildren
  TestimoniRoute: typeof TestimoniRoute
  TokohSentralRoute: typeof TokohSentralRoute
  LayananSlugRoute: typeof LayananSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industri': {
      id: '/industri'
      path: '/industri'
      fullPath: '/industri'
      preLoaderRoute: typeof IndustriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kebijakan-privasi': {
      id: '/kebijakan-privasi'
      path: '/kebijakan-privasi'
      fullPath: '/kebijakan-privasi'
      preLoaderRoute: typeof KebijakanPrivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesehatan': {
      id: '/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof KesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-individu': {
      id: '/layanan-individu'
      path: '/layanan-individu'
      fullPath: '/layanan-individu'
      preLoaderRoute: typeof LayananIndividuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelatihan': {
      id: '/pelatihan'
      path: '/pelatihan'
      fullPath: '/pelatihan'
      preLoaderRoute: typeof PelatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solusi-korporat': {
      id: '/solusi-korporat'
      path: '/solusi-korporat'
      fullPath: '/solusi-korporat'
      preLoaderRoute: typeof SolusiKorporatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syarat-ketentuan': {
      id: '/syarat-ketentuan'
      path: '/syarat-ketentuan'
      fullPath: '/syarat-ketentuan'
      preLoaderRoute: typeof SyaratKetentuanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokoh-sentral': {
      id: '/tokoh-sentral'
      path: '/tokoh-sentral'
      fullPath: '/tokoh-sentral'
      preLoaderRoute: typeof TokohSentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof ArtikelRoute
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof ArtikelRoute
    }
    '/industri/': {
      id: '/industri/'
      path: '/'
      fullPath: '/industri/'
      preLoaderRoute: typeof IndustriIndexRouteImport
      parentRoute: typeof IndustriRoute
    }
    '/industri/$slug': {
      id: '/industri/$slug'
      path: '/$slug'
      fullPath: '/industri/$slug'
      preLoaderRoute: typeof IndustriSlugRouteImport
      parentRoute: typeof IndustriRoute
    }
    '/layanan/$slug': {
      id: '/layanan/$slug'
      path: '/layanan/$slug'
      fullPath: '/layanan/$slug'
      preLoaderRoute: typeof LayananSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/': {
      id: '/program/'
      path: '/'
      fullPath: '/program/'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof ProgramRoute
    }
    '/program/mpp': {
      id: '/program/mpp'
      path: '/mpp'
      fullPath: '/program/mpp'
      preLoaderRoute: typeof ProgramMppRouteImport
      parentRoute: typeof ProgramRoute
    }
    '/tentang-kami/': {
      id: '/tentang-kami/'
      path: '/'
      fullPath: '/tentang-kami/'
      preLoaderRoute: typeof TentangKamiIndexRouteImport
      parentRoute: typeof TentangKamiRoute
    }
    '/tentang-kami/legalitas': {
      id: '/tentang-kami/legalitas'
      path: '/legalitas'
      fullPath: '/tentang-kami/legalitas'
      preLoaderRoute: typeof TentangKamiLegalitasRouteImport
      parentRoute: typeof TentangKamiRoute
    }
  }
}

interface ArtikelRouteChildren {
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
}

const ArtikelRouteChildren: ArtikelRouteChildren = {
  ArtikelSlugRoute: ArtikelSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
}

const ArtikelRouteWithChildren =
  ArtikelRoute._addFileChildren(ArtikelRouteChildren)

interface IndustriRouteChildren {
  IndustriSlugRoute: typeof IndustriSlugRoute
  IndustriIndexRoute: typeof IndustriIndexRoute
}

const IndustriRouteChildren: IndustriRouteChildren = {
  IndustriSlugRoute: IndustriSlugRoute,
  IndustriIndexRoute: IndustriIndexRoute,
}

const IndustriRouteWithChildren = IndustriRoute._addFileChildren(
  IndustriRouteChildren,
)

interface ProgramRouteChildren {
  ProgramMppRoute: typeof ProgramMppRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
}

const ProgramRouteChildren: ProgramRouteChildren = {
  ProgramMppRoute: ProgramMppRoute,
  ProgramIndexRoute: ProgramIndexRoute,
}

const ProgramRouteWithChildren =
  ProgramRoute._addFileChildren(ProgramRouteChildren)

interface TentangKamiRouteChildren {
  TentangKamiLegalitasRoute: typeof TentangKamiLegalitasRoute
  TentangKamiIndexRoute: typeof TentangKamiIndexRoute
}

const TentangKamiRouteChildren: TentangKamiRouteChildren = {
  TentangKamiLegalitasRoute: TentangKamiLegalitasRoute,
  TentangKamiIndexRoute: TentangKamiIndexRoute,
}

const TentangKamiRouteWithChildren = TentangKamiRoute._addFileChildren(
  TentangKamiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRouteWithChildren,
  FaqRoute: FaqRoute,
  IndustriRoute: IndustriRouteWithChildren,
  KebijakanPrivasiRoute: KebijakanPrivasiRoute,
  KesehatanRoute: KesehatanRoute,
  KontakRoute: KontakRoute,
  LayananIndividuRoute: LayananIndividuRoute,
  PelatihanRoute: PelatihanRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ProgramRoute: ProgramRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolusiKorporatRoute: SolusiKorporatRoute,
  SyaratKetentuanRoute: SyaratKetentuanRoute,
  TentangKamiRoute: TentangKamiRouteWithChildren,
  TestimoniRoute: TestimoniRoute,
  TokohSentralRoute: TokohSentralRoute,
  LayananSlugRoute: LayananSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
