/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndustriRouteImport } from './routes/industri'
import { Route as KesehatanRouteImport } from './routes/kesehatan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LayananIndividuRouteImport } from './routes/layanan-individu'
import { Route as PelatihanRouteImport } from './routes/pelatihan'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolusiKorporatRouteImport } from './routes/solusi-korporat'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as TestimoniRouteImport } from './routes/testimoni'
import { Route as ArtikelIndexRouteImport } from './routes/artikel.index'
import { Route as ArtikelSlugRouteImport } from './routes/artikel.$slug'
import { Route as IndustriIndexRouteImport } from './routes/industri.index'
import { Route as IndustriSlugRouteImport } from './routes/industri.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriRoute = IndustriRouteImport.update({
  id: '/industri',
  path: '/industri',
  getParentRoute: () => rootRouteImport,
} as any)
const KesehatanRoute = KesehatanRouteImport.update({
  id: '/kesehatan',
  path: '/kesehatan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananIndividuRoute = LayananIndividuRouteImport.update({
  id: '/layanan-individu',
  path: '/layanan-individu',
  getParentRoute: () => rootRouteImport,
} as any)
const PelatihanRoute = PelatihanRouteImport.update({
  id: '/pelatihan',
  path: '/pelatihan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolusiKorporatRoute = SolusiKorporatRouteImport.update({
  id: '/solusi-korporat',
  path: '/solusi-korporat',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimoniRoute = TestimoniRouteImport.update({
  id: '/testimoni',
  path: '/testimoni',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtikelRoute,
} as any)
const ArtikelSlugRoute = ArtikelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtikelRoute,
} as any)
const IndustriIndexRoute = IndustriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriRoute,
} as any)
const IndustriSlugRoute = IndustriSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/faq': typeof FaqRoute
  '/industri': typeof IndustriRouteWithChildren
  '/kesehatan': typeof KesehatanRoute
  '/kontak': typeof KontakRoute
  '/layanan-individu': typeof LayananIndividuRoute
  '/pelatihan': typeof PelatihanRoute
  '/professionals': typeof ProfessionalsRoute
  '/program': typeof ProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solusi-korporat': typeof SolusiKorporatRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/industri/$slug': typeof IndustriSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/industri/': typeof IndustriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/kesehatan': typeof KesehatanRoute
  '/kontak': typeof KontakRoute
  '/layanan-individu': typeof LayananIndividuRoute
  '/pelatihan': typeof PelatihanRoute
  '/professionals': typeof ProfessionalsRoute
  '/program': typeof ProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solusi-korporat': typeof SolusiKorporatRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/industri/$slug': typeof IndustriSlugRoute
  '/artikel': typeof ArtikelIndexRoute
  '/industri': typeof IndustriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRouteWithChildren
  '/faq': typeof FaqRoute
  '/industri': typeof IndustriRouteWithChildren
  '/kesehatan': typeof KesehatanRoute
  '/kontak': typeof KontakRoute
  '/layanan-individu': typeof LayananIndividuRoute
  '/pelatihan': typeof PelatihanRoute
  '/professionals': typeof ProfessionalsRoute
  '/program': typeof ProgramRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solusi-korporat': typeof SolusiKorporatRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/testimoni': typeof TestimoniRoute
  '/artikel/$slug': typeof ArtikelSlugRoute
  '/industri/$slug': typeof IndustriSlugRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/industri/': typeof IndustriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artikel'
    | '/faq'
    | '/industri'
    | '/kesehatan'
    | '/kontak'
    | '/layanan-individu'
    | '/pelatihan'
    | '/professionals'
    | '/program'
    | '/sitemap.xml'
    | '/solusi-korporat'
    | '/tentang-kami'
    | '/testimoni'
    | '/artikel/$slug'
    | '/industri/$slug'
    | '/artikel/'
    | '/industri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/kesehatan'
    | '/kontak'
    | '/layanan-individu'
    | '/pelatihan'
    | '/professionals'
    | '/program'
    | '/sitemap.xml'
    | '/solusi-korporat'
    | '/tentang-kami'
    | '/testimoni'
    | '/artikel/$slug'
    | '/industri/$slug'
    | '/artikel'
    | '/industri'
  id:
    | '__root__'
    | '/'
    | '/artikel'
    | '/faq'
    | '/industri'
    | '/kesehatan'
    | '/kontak'
    | '/layanan-individu'
    | '/pelatihan'
    | '/professionals'
    | '/program'
    | '/sitemap.xml'
    | '/solusi-korporat'
    | '/tentang-kami'
    | '/testimoni'
    | '/artikel/$slug'
    | '/industri/$slug'
    | '/artikel/'
    | '/industri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtikelRoute: typeof ArtikelRouteWithChildren
  FaqRoute: typeof FaqRoute
  IndustriRoute: typeof IndustriRouteWithChildren
  KesehatanRoute: typeof KesehatanRoute
  KontakRoute: typeof KontakRoute
  LayananIndividuRoute: typeof LayananIndividuRoute
  PelatihanRoute: typeof PelatihanRoute
  ProfessionalsRoute: typeof ProfessionalsRoute
  ProgramRoute: typeof ProgramRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolusiKorporatRoute: typeof SolusiKorporatRoute
  TentangKamiRoute: typeof TentangKamiRoute
  TestimoniRoute: typeof TestimoniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industri': {
      id: '/industri'
      path: '/industri'
      fullPath: '/industri'
      preLoaderRoute: typeof IndustriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesehatan': {
      id: '/kesehatan'
      path: '/kesehatan'
      fullPath: '/kesehatan'
      preLoaderRoute: typeof KesehatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-individu': {
      id: '/layanan-individu'
      path: '/layanan-individu'
      fullPath: '/layanan-individu'
      preLoaderRoute: typeof LayananIndividuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelatihan': {
      id: '/pelatihan'
      path: '/pelatihan'
      fullPath: '/pelatihan'
      preLoaderRoute: typeof PelatihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solusi-korporat': {
      id: '/solusi-korporat'
      path: '/solusi-korporat'
      fullPath: '/solusi-korporat'
      preLoaderRoute: typeof SolusiKorporatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoni': {
      id: '/testimoni'
      path: '/testimoni'
      fullPath: '/testimoni'
      preLoaderRoute: typeof TestimoniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof ArtikelRoute
    }
    '/artikel/$slug': {
      id: '/artikel/$slug'
      path: '/$slug'
      fullPath: '/artikel/$slug'
      preLoaderRoute: typeof ArtikelSlugRouteImport
      parentRoute: typeof ArtikelRoute
    }
    '/industri/': {
      id: '/industri/'
      path: '/'
      fullPath: '/industri/'
      preLoaderRoute: typeof IndustriIndexRouteImport
      parentRoute: typeof IndustriRoute
    }
    '/industri/$slug': {
      id: '/industri/$slug'
      path: '/$slug'
      fullPath: '/industri/$slug'
      preLoaderRoute: typeof IndustriSlugRouteImport
      parentRoute: typeof IndustriRoute
    }
  }
}

interface ArtikelRouteChildren {
  ArtikelSlugRoute: typeof ArtikelSlugRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
}

const ArtikelRouteChildren: ArtikelRouteChildren = {
  ArtikelSlugRoute: ArtikelSlugRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
}

const ArtikelRouteWithChildren =
  ArtikelRoute._addFileChildren(ArtikelRouteChildren)

interface IndustriRouteChildren {
  IndustriSlugRoute: typeof IndustriSlugRoute
  IndustriIndexRoute: typeof IndustriIndexRoute
}

const IndustriRouteChildren: IndustriRouteChildren = {
  IndustriSlugRoute: IndustriSlugRoute,
  IndustriIndexRoute: IndustriIndexRoute,
}

const IndustriRouteWithChildren = IndustriRoute._addFileChildren(
  IndustriRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtikelRoute: ArtikelRouteWithChildren,
  FaqRoute: FaqRoute,
  IndustriRoute: IndustriRouteWithChildren,
  KesehatanRoute: KesehatanRoute,
  KontakRoute: KontakRoute,
  LayananIndividuRoute: LayananIndividuRoute,
  PelatihanRoute: PelatihanRoute,
  ProfessionalsRoute: ProfessionalsRoute,
  ProgramRoute: ProgramRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolusiKorporatRoute: SolusiKorporatRoute,
  TentangKamiRoute: TentangKamiRoute,
  TestimoniRoute: TestimoniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
